# Pre-commit that runs locally
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '\.(yaml|yml)$'
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.21.2
    hooks:
      - id: sqlfmt
        name: SQL formatter
        language_version: python
        additional_dependencies: [".[jinjafmt]"]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: ^data/

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.2.0
    hooks:
      # - id: check-model-has-description
      - id: check-model-has-tests-by-group
        args: ["--tests", "not_null", "--test-cnt", "1", "--"]
      - id: check-model-has-tests-by-group
        args:
          [
            "--tests",
            "unique",
            "unique_combination_of_columns",
            "--test-cnt",
            "1",
            "--",
          ]
      - id: check-macro-has-description
        files: ^(macros/).*$
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 2.3.5
  #   hooks:
  #     - id: sqlfluff-fix
  #       args: [--config, "./conf_local/.sqlfluff", --show-lint-violations]
  #       additional_dependencies:
  #         ["dbt-core==1.8.3", "dbt-snowflake==1.8.3", "sqlfluff-templater-dbt"]
